version: "3.8"

services:
  db:
    image: postgres:13
    platform: linux/amd64
    container_name: mattermost-db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    networks:
      - mattermost-network
  app:
    image: mattermost/mattermost-team-edition:latest
    platform: linux/amd64
    container_name: mattermost-app
    restart: unless-stopped
    volumes:
      - app-data:/mattermost/data
    environment:
      - MM_CONFIG=/mattermost/config/config.json
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
    depends_on:
      - db
    ports:
      - "8065:8065"
    networks:
      - mattermost-network

networks:
  mattermost-network:

volumes:
  db-data:
  app-data:

